global:
  # scrape_interval: メトリクスの収集間隔(def: 1m)
  scrape_interval: 1s
  # evaluation_interval: ルールの評価間隔(def: 1m)
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ${ENV_MONITORING_TARGETS}
