---

services:
  # Grafana
  # user: admin
  # pass: admin
  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ${PWD}/plg-stack/grafana/etc/grafana/provisioning/datasources/
        target: /etc/grafana/provisioning/datasources/
  # https://github.com/prometheus/prometheus/tree/main?tab=readme-ov-file#docker-images
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./tmp/prometheus.yml
        target: /etc/prometheus/prometheus.yml
  # Loki
  loki:
    image: grafana/loki:3.2.1
    ports:
      - 3100:3100
